2025-05-30 21:54:33,203 - ERROR - Error while reading YAML file
2025-05-30 22:21:11,559 - ERROR - Error while reading YAML file
2025-05-30 22:29:45,383 - INFO - Succesfully read the YAML file
2025-05-30 22:29:45,384 - INFO - Data Ingestion Started....
2025-05-30 22:29:45,384 - INFO - Starting Data Ingestion Process....
2025-05-30 22:29:45,384 - ERROR - File not found: Source file not found: E:/bigdata\anime.csv
2025-05-30 22:29:45,384 - ERROR - CustomException: Error in D:\DataProjects\DataProjects\Anime\src\data_ingestion.py , line 40 : Source file not found
2025-05-30 22:29:45,384 - INFO - Data Ingestion DONE...
2025-05-30 22:34:38,418 - INFO - Succesfully read the YAML file
2025-05-30 22:37:15,627 - INFO - Succesfully read the YAML file
2025-05-30 22:37:15,628 - INFO - Data Ingestion Started....
2025-05-30 22:37:15,628 - INFO - Starting Data Ingestion Process....
2025-05-30 22:37:15,628 - ERROR - File not found: Source file not found: E:/bigdata\anime.csv
2025-05-30 22:37:15,628 - ERROR - CustomException: Error in D:\DataProjects\DataProjects\Anime\src\data_ingestion.py , line 40 : Source file not found
2025-05-30 22:37:15,628 - INFO - Data Ingestion DONE...
2025-05-30 22:38:23,447 - INFO - Succesfully read the YAML file
2025-05-30 22:38:23,448 - INFO - Data Ingestion Started....
2025-05-30 22:38:23,448 - INFO - Starting Data Ingestion Process....
2025-05-30 22:38:23,450 - ERROR - File not found: Source file not found: E:/bigdata\anime.csv
2025-05-30 22:38:23,450 - ERROR - CustomException: Error in D:\DataProjects\DataProjects\Anime\src\data_ingestion.py , line 55 : Source file not found
2025-05-30 22:38:23,451 - INFO - Data Ingestion DONE...
2025-05-30 22:39:07,386 - INFO - Succesfully read the YAML file
2025-05-30 22:39:07,387 - INFO - Data Ingestion Started....
2025-05-30 22:39:07,387 - INFO - Starting Data Ingestion Process....
2025-05-30 22:39:07,389 - ERROR - File not found: Source file not found: E:/bigdata\anime.csv
2025-05-30 22:39:07,389 - ERROR - CustomException: Error in D:\DataProjects\DataProjects\Anime\src\data_ingestion.py , line 55 : Source file not found
2025-05-30 22:39:07,390 - INFO - Data Ingestion DONE...
2025-05-30 22:41:58,025 - INFO - Succesfully read the YAML file
2025-05-30 22:41:58,025 - INFO - Data Ingestion Started....
2025-05-30 22:41:58,025 - INFO - Starting Data Ingestion Process....
2025-05-30 22:41:58,028 - INFO - Copying file: anime.csv
2025-05-30 22:41:58,141 - INFO - File copied successfully: anime.csv
2025-05-30 22:41:58,142 - INFO - File anime.csv: 5.40 MB
2025-05-30 22:41:58,143 - INFO - Copying file: anime_with_synopsis.csv
2025-05-30 22:41:58,274 - INFO - File copied successfully: anime_with_synopsis.csv
2025-05-30 22:41:58,275 - INFO - File anime_with_synopsis.csv: 6.89 MB
2025-05-30 22:41:58,276 - INFO - Processing large file: animelist.csv - limiting to 5,000,000 rows
2025-05-30 22:42:09,341 - INFO - Large file processed: Only 5,000,000 rows saved to D:\DataProjects\DataProjects\Anime\artifacts/raw\animelist.csv
2025-05-30 22:42:09,342 - INFO - File animelist.csv: 87.04 MB
2025-05-30 22:42:09,361 - INFO - Data Ingestion Completed...
2025-05-30 22:42:09,361 - INFO - Data Ingestion DONE...
